.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:Configuration-github| image:: https://img.shields.io/badge/pyEDAA-Configuration-ffca28.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=ff8f00
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration
.. |SHIELD:png:Configuration-github| image:: https://raster.shields.io/badge/pyEDAA-Configuration-ffca28.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=ff8f00
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration

.. # Sourcecode license
.. |SHIELD:svg:Configuration-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:Configuration-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:Configuration-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/tags
.. |SHIELD:png:Configuration-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/tags

.. # GitHub release
.. |SHIELD:svg:Configuration-release| image:: https://img.shields.io/github/v/release/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/releases/latest
.. |SHIELD:png:Configuration-release| image:: https://raster.shields.io/github/v/release/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/releases/latest

.. # GitHub release date
.. |SHIELD:svg:Configuration-date| image:: https://img.shields.io/github/release-date/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/releases
.. |SHIELD:png:Configuration-date| image:: https://raster.shields.io/github/release-date/edaa-org/pyEDAA.Configuration?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:Configuration-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/network/dependents
.. |SHIELD:png:Configuration-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:Configuration-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pyEDAA.Configuration/Pipeline/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/actions/workflows/Pipeline.yml
.. |SHIELD:png:Configuration-gha-test| image:: https://raster.shields.io/github/workflow/status/edaa-org/pyEDAA.Configuration/Pipeline/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:Configuration-codacy-quality| image:: https://img.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Configuration
.. |SHIELD:png:Configuration-codacy-quality| image:: https://raster.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Configuration

.. # Codacy - coverage
.. |SHIELD:svg:Configuration-codacy-coverage| image:: https://img.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Configuration
.. |SHIELD:png:Configuration-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.Configuration

.. # Codecov - coverage
.. |SHIELD:svg:Configuration-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.Configuration
.. |SHIELD:png:Configuration-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.Configuration

.. # Libraries - source rank
.. |SHIELD:svg:Configuration-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Configuration/sourcerank
.. |SHIELD:png:Configuration-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Configuration/sourcerank

.. # PyPI tag
.. |SHIELD:svg:Configuration-pypi-tag| image:: https://img.shields.io/pypi/v/pyEDAA.Configuration?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.Configuration/
.. |SHIELD:png:Configuration-pypi-tag| image:: https://raster.shields.io/pypi/v/pyEDAA.Configuration?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.Configuration/

.. # PyPI project status
.. |SHIELD:svg:Configuration-pypi-status| image:: https://img.shields.io/pypi/status/pyEDAA.Configuration?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:Configuration-pypi-status| image:: https://raster.shields.io/pypi/status/pyEDAA.Configuration?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:Configuration-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyEDAA.Configuration?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:Configuration-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyEDAA.Configuration?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:Configuration-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Configuration
.. |SHIELD:png:Configuration-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyEDAA.Configuration?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.Configuration

.. # Requires - status
.. |SHIELD:svg:Configuration-req-status| image:: https://img.shields.io/requires/github/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.Configuration/requirements/?branch=main
.. |SHIELD:png:Configuration-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pyEDAA.Configuration?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.Configuration/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:Configuration-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:Configuration-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.Configuration/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:Configuration-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.Configuration&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.Configuration%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.Configuration/
.. |SHIELD:png:Configuration-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.Configuration&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.Configuration%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.Configuration/

.. # Gitter
.. |SHIELD:svg:Configuration-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:Configuration-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
